=== CMSgov/price-transparency-guide/schemas/in-network-rates/in-network-rates.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "in_network": {
      "type": "object",
      "properties": {
        "negotiation_arrangement": {
          "enum": [
            "ffs",
            "bundle",
            "capitation"
          ]
        },
        "name": {
          "type": "string"
        },
        "billing_code_type": {
          "enum": [
            "CPT",
            "HCPCS",
            "ICD",
            "MS-DRG",
            "R-DRG",
            "S-DRG",
            "APS-DRG",
            "AP-DRG",
            "APR-DRG",
            "APC",
            "NDC",
            "HIPPS",
            "LOCAL",
            "EAPG",
            "CDT",
            "RC",
            "CSTM-ALL"
          ]
        },
        "billing_code_type_version": {
          "type": "string"
        },
        "billing_code": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "negotiated_rates": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/negotiated_rates"
          },
          "default": []
        },
        "covered_services": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/covered_services"
          },
          "default": []
        },
        "bundled_codes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/bundled_codes"
          },
          "default": []
        }
      },
      "required": [
        "negotiation_arrangement",
        "name",
        "billing_code_type",
        "billing_code_type_version",
        "billing_code",
        "negotiated_rates",
        "description"
      ]
    },
    "bundled_codes": {
      "type": "object",
      "properties": {
        "billing_code_type": {
          "enum": [
            "CPT",
            "HCPCS",
            "ICD",
            "MS-DRG",
            "R-DRG",
            "S-DRG",
            "APS-DRG",
            "AP-DRG",
            "APR-DRG",
            "APC",
            "NDC",
            "HIPPS",
            "LOCAL",
            "EAPG",
            "CDT",
            "RC",
            "CSTM-ALL"
          ]
        },
        "billing_code_type_version": {
          "type": "string"
        },
        "billing_code": {
          "type": "string"
        },
        "description": {
          "type": "string"
        }
      },
      "required": [
        "billing_code_type",
        "billing_code_type_version",
        "billing_code",
        "description"
      ]
    },
    "covered_services": {
      "type": "object",
      "properties": {
        "billing_code_type": {
          "enum": [
            "CPT",
            "HCPCS",
            "ICD",
            "MS-DRG",
            "R-DRG",
            "S-DRG",
            "APS-DRG",
            "AP-DRG",
            "APR-DRG",
            "APC",
            "NDC",
            "HIPPS",
            "LOCAL",
            "EAPG",
            "CDT",
            "RC",
            "CSTM-ALL"
          ]
        },
        "billing_code_type_version": {
          "type": "string"
        },
        "billing_code": {
          "type": "string"
        },
        "description": {
          "type": "string"
        }
      },
      "required": [
        "billing_code_type",
        "billing_code_type_version",
        "billing_code",
        "description"
      ]
    },
    "provider_references": {
      "type": "object",
      "properties": {
        "provider_group_id": {
          "type": "number"
        },
        "provider_groups": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/providers"
          },
          "uniqueItems": true,
          "default": []
        },
        "location": {
          "type": "string",
          "format": "uri",
          "pattern": "^https://"
        }
      },
      "anyOf": [
        {
          "required": [
            "location"
          ]
        },
        {
          "required": [
            "provider_groups"
          ]
        }
      ],
      "required": [
        "provider_group_id"
      ]
    },
    "providers": {
      "type": "object",
      "properties": {
        "npi": {
          "type": "array",
          "items": {
            "type": "number"
          },
          "uniqueItems": true,
          "default": []
        },
        "tin": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "ein",
                "npi"
              ]
            },
            "value": {
              "type": "string"
            }
          },
          "required": [
            "type",
            "value"
          ]
        }
      },
      "required": [
        "npi",
        "tin"
      ]
    },
    "negotiated_rates": {
      "type": "object",
      "properties": {
        "negotiated_prices": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/negotiated_price"
          },
          "uniqueItems": true,
          "default": []
        },
        "provider_groups": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/providers"
          },
          "uniqueItems": true,
          "default": []
        },
        "provider_references": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/provider_references/properties/provider_group_id"
          },
          "uniqueItems": true,
          "default": []
        }
      },
      "oneOf": [
        {
          "required": [
            "provider_references"
          ]
        },
        {
          "required": [
            "provider_groups"
          ]
        }
      ],
      "required": [
        "negotiated_prices"
      ]
    },
    "negotiated_price": {
      "type": "object",
      "properties": {
        "service_code": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "01",
              "02",
              "03",
              "04",
              "05",
              "06",
              "07",
              "08",
              "09",
              "10",
              "11",
              "12",
              "13",
              "14",
              "15",
              "16",
              "17",
              "18",
              "19",
              "20",
              "21",
              "22",
              "23",
              "24",
              "25",
              "26",
              "27",
              "28",
              "29",
              "30",
              "31",
              "32",
              "33",
              "34",
              "35",
              "36",
              "37",
              "38",
              "39",
              "40",
              "41",
              "42",
              "43",
              "44",
              "45",
              "46",
              "47",
              "48",
              "49",
              "50",
              "51",
              "52",
              "53",
              "54",
              "55",
              "56",
              "57",
              "58",
              "59",
              "60",
              "61",
              "62",
              "63",
              "64",
              "65",
              "66",
              "67",
              "68",
              "69",
              "70",
              "71",
              "72",
              "73",
              "74",
              "75",
              "76",
              "77",
              "78",
              "79",
              "80",
              "81",
              "82",
              "83",
              "84",
              "85",
              "86",
              "87",
              "88",
              "89",
              "90",
              "91",
              "92",
              "93",
              "94",
              "95",
              "96",
              "97",
              "98",
              "99",
              "CSTM-00"
            ]
          },
          "uniqueItems": true
        },
        "billing_class": {
          "enum": [
            "professional",
            "institutional",
            "both"
          ]
        },
        "negotiated_type": {
          "enum": [
            "negotiated",
            "derived",
            "fee schedule",
            "percentage",
            "per diem"
          ]
        },
        "billing_code_modifier": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true,
          "default": []
        },
        "diagnosis_code": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true,
          "default": []
        },
        "negotiated_rate": {
          "type": "number"
        },
        "expiration_date": {
          "type": "string",
          "description": "This is a date format of YYYY-MM-DD"
        },
        "additional_information": {
          "type": "string",
          "description": "In situations in which alternative reimbursement arrangements can neither be expressed as a dollar amount nor as a percentage, this open text field can be used to provide information such as, a description of the formula, variables, methodology or other information necessary to understand the arrangement. The open text field may be utilized for reporting only if a plan or issuer cannot disclose its in-network rates as a dollar amount or a percentage."
        }
      },
      "required": [
        "negotiated_type",
        "billing_class",
        "negotiated_rate",
        "expiration_date"
      ],
      "oneOf": [
        {
          "properties": {
            "billing_class": {
              "enum": [
                "professional"
              ]
            }
          },
          "required": [
            "service_code"
          ]
        },
        {
          "properties": {
            "billing_class": {
              "enum": [
                "institutional",
                "both"
              ]
            }
          }
        }
      ]
    }
  },
  "type": "object",
  "properties": {
    "reporting_entity_name": {
      "type": "string"
    },
    "reporting_entity_type": {
      "type": "string"
    },
    "plan_name": {
      "type": "string"
    },
    "plan_id_type": {
      "type": "string"
    },
    "plan_id": {
      "type": "string"
    },
    "plan_market_type": {
      "enum": [
        "group",
        "individual"
      ]
    },
    "last_updated_on": {
      "type": "string",
      "description": "This is a date format of YYYY-MM-DD"
    },
    "version": {
      "type": "string"
    },
    "provider_references": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/provider_references"
      },
      "default": []
    },
    "in_network": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/in_network"
      },
      "default": []
    }
  },
  "required": [
    "reporting_entity_name",
    "reporting_entity_type",
    "last_updated_on",
    "in_network",
    "version"
  ],
  "dependentRequired": {
    "plan_name": [
      "plan_id_type",
      "plan_id",
      "plan_market_type"
    ],
    "plan_id_type": [
      "plan_name",
      "plan_id",
      "plan_market_type"
    ],
    "plan_id": [
      "plan_name",
      "plan_id_type",
      "plan_market_type"
    ],
    "plan_market_type": [
      "plan_name",
      "plan_id_type",
      "plan_id"
    ]
  }
}

=== CMSgov/price-transparency-guide/examples/in-network-rates/in-network-rates-capitation-single-plan-sample.json
{
  "reporting_entity_name": "cms",
  "reporting_entity_type": "cms",
  "plan_name": "medicaid",
  "plan_id_type": "hios",
  "plan_id": "1111111111",
  "plan_market_type": "individual",
  "last_updated_on": "2020-08-27",
  "version": "1.0.0",
  "in_network": [{ 
    "negotiation_arrangement": "capitation",
    "name": "Primary Care Capitation",
    "description": "Typical items and services for a primary care provider",
    "billing_code_type": "CPT",
    "billing_code_type_version": "2020",
    "billing_code": "27447",
    "negotiated_rates": [{
      "provider_groups": [{
        "npi": [1111111111, 2222222222, 3333333333, 4444444444, 5555555555],
         "tin":{
           "type": "ein",
           "value": "11-1111111"
         }
      },{
        "npi": [1111111111, 2222222222, 3333333333, 4444444444, 5555555555],
         "tin":{
           "type": "ein",
           "value": "22-2222222"
         }
      }],
      "negotiated_prices": [{
        "negotiated_type": "negotiated",
        "negotiated_rate": 20000.00,
        "expiration_date": "2022-01-01",
        "billing_class": "institutional"
      }]
    },{
      "provider_groups":[{
        "npi": [6666666666, 7777777777, 8888888888, 9999999999],
         "tin":{
           "type": "ein",
           "value": "22-2222222"
         }
      }],
      "negotiated_prices": [{
        "negotiated_type": "negotiated",
        "negotiated_rate": 25000.00,
        "expiration_date": "2022-01-01",
        "service_code": ["05", "06", "07"],
        "billing_class": "professional"
      }]
    }],
    "covered_services": [{
      "billing_code_type": "CPT",
      "billing_code_type_version": "2020",
      "billing_code": "27447",
      "description": "Under Repair, Revision, and/or Reconstruction Procedures on the Femur (Thigh Region) and Knee Joint"
    },{
      "billing_code_type": "CPT",
      "billing_code_type_version": "2020",
      "billing_code": "27446",
      "description": "Under Repair, Revision, and/or Reconstruction Procedures on the Femur (Thigh Region) and Knee Joint"
    }]
  }]
}

=== CMSgov/price-transparency-guide/examples/in-network-rates/in-network-rates-multiple-plans-sample.json
{
  "reporting_entity_name": "cms",
  "reporting_entity_type": "cms",
  "last_updated_on": "2020-08-27",
  "version": "1.0.0",
  "in_network": [{
    "negotiation_arrangement": "ffs",
    "name": "Knee Replacement",
    "billing_code_type": "CPT",
    "billing_code_type_version": "2020",
    "billing_code": "27447",
    "description": "Arthroplasty, knee condyle and plateau, medial and lateral compartments",
    "negotiated_rates": [{
      "provider_groups": [{
        "npi": [1111111111, 2222222222, 3333333333, 4444444444, 5555555555],
        "tin":{
          "type": "ein",
          "value": "11-1111111"
        }
      },{
        "npi": [1111111111, 2222222222, 3333333333, 4444444444, 5555555555],
        "tin":{
          "type": "ein",
          "value": "22-2222222"
        }
      }],
      "negotiated_prices": [{
        "negotiated_type": "negotiated",
        "negotiated_rate": 123.45,
        "expiration_date": "2022-01-01",
        "service_code": ["18", "19", "11"],
        "billing_class": "professional",
        "billing_code_modifier": ["AS"]
      },{
        "negotiated_type": "negotiated",
        "negotiated_rate": 1230.45,
        "expiration_date": "2022-01-01",
        "billing_class": "institutional"
      }]
      },{
      "provider_groups": [{
        "npi": [6666666666, 7777777777, 8888888888, 9999999999],
        "tin":{
          "type": "ein",
          "value": "22-2222222"
        }
      }],
      "negotiated_prices": [{
        "negotiated_type": "negotiated",
        "negotiated_rate": 120.45,
        "expiration_date": "2022-01-01",
        "service_code": ["05", "06", "07"],
        "billing_class": "professional"
      }]
    }]
  },{
    "negotiation_arrangement": "ffs",
    "name": "Femur and Knee Joint Repair",
    "billing_code_type": "CPT",
    "billing_code_type_version": "2020",
    "billing_code": "27448",
    "description": "Under Repair, Revision, and/or Reconstruction Procedures on the Femur (Thigh Region) and Knee Joint",
    "negotiated_rates": [{
      "provider_groups": [{
        "npi": [1111111111, 2222222222, 3333333333, 4444444444, 5555555555],
        "tin":{
          "type": "ein",
          "value": "11-1111111"
        }
      },{
        "npi": [1111111111, 2222222222, 3333333333, 4444444444, 5555555555],
        "tin":{
          "type": "ein",
          "value": "22-2222222"
        }
      }],
      "negotiated_prices": [{
        "negotiated_type": "negotiated",
        "negotiated_rate": 12003.45,
        "expiration_date": "2022-01-01",
        "service_code": ["18", "19", "11"],
        "billing_class": "professional"
      }]
    },{
      "provider_groups": [{
        "npi": [6666666666],
        "tin":{
          "type": "npi",
          "value": "6666666666"
        }
      }],
      "negotiated_prices": [{
        "negotiated_type": "negotiated",
        "negotiated_rate": 12.45,
        "expiration_date": "2022-01-01",
        "service_code": ["18", "19", "11"],
        "billing_class": "institutional"
      }]
    }]
  }]
}

=== CMSgov/price-transparency-guide/examples/in-network-rates/in-network-rates-fee-for-service-single-plan-sample.json
{
  "reporting_entity_name": "medicare",
  "reporting_entity_type": "medicare",
  "plan_name": "medicaid",
  "plan_id_type": "hios",
  "plan_id": "1111111111",
  "plan_market_type": "individual",
  "last_updated_on": "2020-08-27",
  "version": "1.0.0",
  "provider_references":[{
    "provider_group_id": 1,
    "provider_groups": [{
      "npi": [1111111111, 2222222222, 3333333333, 4444444444, 5555555555],
      "tin":{
        "type": "ein",
        "value": "11-1111111"
      }
    },{
      "npi": [1111111111, 2222222222, 3333333333, 4444444444, 5555555555],
      "tin":{
        "type": "ein",
        "value": "22-2222222"
      }
    }]
  },{
    "provider_group_id": 2,
    "location": "https://www.cms.gov/some_provider_group.json"
  }],
  "in_network": [{
    "negotiation_arrangement": "ffs",
    "name": "Knee Replacement",
    "billing_code_type": "CPT",
    "billing_code_type_version": "2020",
    "billing_code": "27447",
    "description": "Arthroplasty, knee condyle and plateau, medial and lateral compartments",
    "negotiated_rates": [{
      "provider_groups": [{
        "npi": [1111111111, 2222222222, 3333333333, 4444444444, 5555555555],
        "tin":{
          "type": "ein",
          "value": "11-1111111"
        }
      },{
        "npi": [1111111111, 2222222222, 3333333333, 4444444444, 5555555555],
        "tin":{
          "type": "ein",
          "value": "22-2222222"
        }
      }],
      "negotiated_prices": [{
        "negotiated_type": "negotiated",
        "negotiated_rate": 123.45,
        "expiration_date": "2022-01-01",
        "service_code": ["18", "19", "11"],
        "billing_class": "professional",
        "billing_code_modifier": ["AS"]
      },{
        "negotiated_type": "negotiated",
        "negotiated_rate": 1230.45,
        "expiration_date": "2022-01-01",
        "billing_class": "institutional"
      }]
      },{
      "provider_groups": [{
        "npi": [6666666666, 7777777777, 8888888888, 9999999999],
        "tin":{
          "type": "ein",
          "value": "22-2222222"
        }
      }],
      "negotiated_prices": [{
        "negotiated_type": "negotiated",
        "negotiated_rate": 120.45,
        "expiration_date": "2022-01-01",
        "service_code": ["05", "06", "07"],
        "billing_class": "professional"
      }]
    }]
  },{
    "negotiation_arrangement": "ffs",
    "name": "Femur and Knee Joint Repair",
    "billing_code_type": "CPT",
    "billing_code_type_version": "2020",
    "billing_code": "27448",
    "description": "Under Repair, Revision, and/or Reconstruction Procedures on the Femur (Thigh Region) and Knee Joint",
    "negotiated_rates": [{
      "provider_references": [1],
      "negotiated_prices": [{
        "negotiated_type": "negotiated",
        "negotiated_rate": 12003.45,
        "expiration_date": "2022-01-01",
        "service_code": ["CSTM-00"],
        "billing_class": "professional"
      }]
    },{
      "provider_groups": [{
        "npi": [6666666666],
        "tin":{
          "type": "npi",
          "value": "6666666666"
        }
      }],
      "negotiated_prices": [{
        "negotiated_type": "negotiated",
        "negotiated_rate": 12.45,
        "expiration_date": "2022-01-01",
        "service_code": ["18", "19", "11"],
        "billing_class": "institutional"
      }]
    }]
  }]
}
