=== CMSgov/price-transparency-guide/schemas/prescription-drugs/prescription-drugs.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "drugs": {
      "type": "object",
      "properties": {
        "drug_name": { "type": "string" },
        "drug_type": { "enum": [ "branded", "generic", "biosimilar" ] },
        "ndc": { "type": "string" },
        "prices": {
          "type": "array",
          "items": { "$ref": "#/definitions/prices" },
          "default": []
        }
      },
      "required": [ "drug_name", "drug_type", "ndc", "prices" ]
    },

    "prices": {
      "type": "object",
      "properties": {
        "historical_net_price": { "type": "number" },
        "historical_net_reporting_period": { "type": "string", "format": "date" },
        "negotiated_rate": { "type": "number" },
        "administrative_fee": { "type": "number" },
        "dispensing_fee": { "type": "number" },
        "transaction_fee": { "type": "number" },
        "tin": { "type": "string" },
        "service_code": {
          "type": "string",
          "$ref": "https://www.cms.gov/Medicare/Coding/place-of-service-codes/Place_of_Service_Code_Set"
        },
        "npi": { 
          "type": "array",
          "items": { "type": "number" },
          "default": [],
          "uniqueItems": true
        },
        "pharmacies": {
          "type": "array",
          "items": { "$ref": "#/definitions/pharmacies" },
          "default": []
        }
      },
      "required": [ "historical_net_price", "historical_net_reporting_period", "negotiated_rate", "administrative_fee", "dispensing_fee", "transaction_fee", "tin", "service_code" ]
    },

    "pharmacies": {
      "type": "object",
      "properties": {
        "pharmacy_id_type": { "enum": [ "ncpdp id", "ncpdp chain code", "npi" ] },
        "pharmacy_ids": { 
          "type": "array",
          "items": { "type": "number" },
          "default": [],
          "uniqueItems": true
        }
      },
      "required": [ "pharmacy_id_type", "pharmacy_ids" ]
    }
  },


  "type": "object",
  "properties": {
    "reporting_entity_name": { "type": "string" },
    "reporting_entity_type": { "type": "string" },
    "plan_name": { "type": "string" },
    "plan_id_type": { "type": "string" },
    "plan_id": { "type": "string" },
    "plan_market_type": { "enum": [ "group", "individual" ] },
    "last_updated_on": { "type": "string", "format": "date" },
    "drugs": {
      "type": "array",
      "items": { "$ref": "#/definitions/drugs" },
      "default": []
    }
  },
  "required": ["reporting_entity_name", "reporting_entity_type", "plan_name", "plan_id_type", "plan_id", "plan_market_type", "last_updated_on"]
}

=== CMSgov/price-transparency-guide/examples/prescription-drugs/prescription-drugs.json
{
  "reporting_entity_name": "medicare",
  "reporting_entity_type": "medicare",
  "plan_name": "medicare",
  "plan_id_type": "HIOS",
  "plan_id": "12345XX9876543",
  "plan_market_type": "individual",
  "last_updated_on": "2020-08-27",
  "drugs": [{
    "drug_name": "Simvastatin", 
    "drug_type": "generic", 
    "ndc": "16729-004",
      
    "prices": [{ 
      "historical_net_price": 0.01,
      "historical_net_reporting_period": "2020-08-28",
      "negotiated_rate": 0.1,
      "administrative_fee": 0.02,
      "dispensing_fee": 2,
      "transaction_fee": 0.005,
      "tin": "11-1111111",
      "service_code": "01",
      "npi": [ 2222222222, 33333333333, 4444444444, 555555555 ],

      "pharmacies":[{
        "pharmacy_id_type": "ncpdp id",
        "pharmacy_ids": [ 1111111, 22222222, 3333333, 4444444 ]
      },{
        "pharmacy_id_type": "ncpdp chain code",
        "pharmacy_ids": [ 1111111, 22222222, 3333333, 4444444 ]
      },{
        "pharmacy_id_type": "npi",
        "pharmacy_ids": [ 111111111, 2222222222, 333333333, 444444444 ]
      }]

    }]
  }]
}
